name: Regenerate documentation

on:
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
    - run: npm ci
    - run: npm run docs-html
    - run: git checkout github-pages
    - run: ls -A -1 --ignore '.git' --ignore 'docs' | xargs rm -f
    - run: mv -f docs/* ./ && rmdir docs
    - run: git add * && git commit -m "Docs updated -- $(date)" && git push origin github-pages
